### ISSUE TITLE
pythonprop.png - make install error

### ISSUE THREAD

**Issue by wa6ezv** [jawatson/pythonprop#10] opened 2020-10-02 19:49 UTC
Stumped!!!!

Making install in data
make[1]: Entering directory '/home/pi/Downloads/pythonprop-0.30/data'
make[1]: *** No rule to make target 'pythonprop.png', needed by 'all-am'.  Stop.
make[1]: Leaving directory '/home/pi/Downloads/pythonprop-0.30/data'
make: *** [Makefile:416: install-recursive] Error 1

**Comment by jawatson** [comment] 2020-10-03 14:53
Thanks for reporting this - the error was caused by a missing .png file in the distribution.  This should be fixed in v30.1.

**Closed as completed** 2020-10-03 14:53 UTC
